name: whole-kale-catalog
favicon: null
layout_spectrum: 0.3793472405523062
typography_spectrum: 0.5548007292672992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.01370998122729361
  lightness: 0.2597201440948993
  saturation: 0.9175668067764491
  rhythmicContrast: 0.6977363068144768
purpose: []
